# Generated by Django 2.1.2 on 2019-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.FileField(upload_to=''),
        ),
    ]
