# Generated by Django 2.1.2 on 2019-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190210_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
